import { ROLES } from "@/backend/constants/roles";

export const PERMISSIONS = Object.freeze({
  PLATFORM_ALL: "platform:*",
  COMPANY_MANAGE: "company:manage",
  USER_MANAGE: "user:manage",
  PARTICIPANT_MANAGE: "participant:manage",
  WORKER_MANAGE: "worker:manage",
  SHIFT_VIEW: "shift:view",
  SHIFT_MANAGE: "shift:manage",
  SHIFT_NOTE_SUBMIT: "shift-note:submit",
  INCIDENT_CREATE: "incident:create",
  BUDGET_VIEW: "budget:view",
  REPORT_VIEW: "report:view",
  AUDIT_VIEW: "audit:view"
});

export const ROLE_PERMISSIONS = {
  [ROLES.SUPER_ADMIN]: [
    PERMISSIONS.PLATFORM_ALL,
    PERMISSIONS.COMPANY_MANAGE,
    PERMISSIONS.USER_MANAGE,
    PERMISSIONS.PARTICIPANT_MANAGE,
    PERMISSIONS.WORKER_MANAGE,
    PERMISSIONS.SHIFT_VIEW,
    PERMISSIONS.SHIFT_MANAGE,
    PERMISSIONS.REPORT_VIEW,
    PERMISSIONS.AUDIT_VIEW
  ],
  [ROLES.COMPANY_ADMIN]: [
    PERMISSIONS.USER_MANAGE,
    PERMISSIONS.PARTICIPANT_MANAGE,
    PERMISSIONS.WORKER_MANAGE,
    PERMISSIONS.SHIFT_VIEW,
    PERMISSIONS.SHIFT_MANAGE,
    PERMISSIONS.BUDGET_VIEW,
    PERMISSIONS.REPORT_VIEW,
    PERMISSIONS.AUDIT_VIEW
  ],
  [ROLES.STATE_MANAGER]: [
    PERMISSIONS.PARTICIPANT_MANAGE,
    PERMISSIONS.WORKER_MANAGE,
    PERMISSIONS.SHIFT_VIEW,
    PERMISSIONS.SHIFT_MANAGE,
    PERMISSIONS.REPORT_VIEW
  ],
  [ROLES.SUPPORT_COORDINATOR]: [
    PERMISSIONS.PARTICIPANT_MANAGE,
    PERMISSIONS.SHIFT_VIEW,
    PERMISSIONS.SHIFT_MANAGE,
    PERMISSIONS.BUDGET_VIEW,
    PERMISSIONS.INCIDENT_CREATE
  ],
  [ROLES.SUPPORT_WORKER]: [
    PERMISSIONS.SHIFT_VIEW,
    PERMISSIONS.SHIFT_NOTE_SUBMIT,
    PERMISSIONS.INCIDENT_CREATE
  ]
};

export const DEFAULT_ROLE_PERMISSIONS = ROLE_PERMISSIONS[ROLES.SUPPORT_WORKER];
